version: "3"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - mercado-bitcoin-network

    #Nginx Service
    webserver:
        image: nginx:stable-alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
            - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - mercado-bitcoin-network

    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mercado_bitcoin_db
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - mercado-bitcoin-network

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        networks:
            - mercado-bitcoin-network

#Docker Networks
networks:
    mercado-bitcoin-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
